// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';

export function DiscoverNetworkDevices():Promise<Array<network.Device>>;

export function GetLocalHostname():Promise<string>;
