// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverNetworkDevices() {
  return window['go']['main']['App']['DiscoverNetworkDevices']();
}

export function GetLocalHostname() {
  return window['go']['main']['App']['GetLocalHostname']();
}
