// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';
import {security} from '../models';

export function DiscoverNetworkDevices():Promise<Array<network.Device>>;

export function GetLocalHostname():Promise<string>;

export function GetPairedDevices():Promise<Array<security.PairedDevice>>;

export function PairWithDevice(arg1:security.PairedDevice):Promise<void>;
