// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';
import {fs} from '../models';
import {security} from '../models';
import {system} from '../models';

export function DiscoverNetworkDevices():Promise<Array<network.Device>>;

export function GenerateLocalManifest(arg1:string):Promise<Array<fs.ManifestItem>>;

export function GetLocalHostname():Promise<string>;

export function GetPairedDevices():Promise<Array<security.PairedDevice>>;

export function GetRootPaths():Promise<Array<fs.FileNode>>;

export function GetSystemStats():Promise<system.SystemStats>;

export function ListDirectory(arg1:string):Promise<Array<fs.FileNode>>;

export function PairWithDevice(arg1:security.PairedDevice):Promise<void>;
