// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverNetworkDevices() {
  return window['go']['main']['App']['DiscoverNetworkDevices']();
}

export function GenerateLocalManifest(arg1) {
  return window['go']['main']['App']['GenerateLocalManifest'](arg1);
}

export function GetLocalHostname() {
  return window['go']['main']['App']['GetLocalHostname']();
}

export function GetPairedDevices() {
  return window['go']['main']['App']['GetPairedDevices']();
}

export function GetRootPaths() {
  return window['go']['main']['App']['GetRootPaths']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function PairWithDevice(arg1) {
  return window['go']['main']['App']['PairWithDevice'](arg1);
}
